# This file configures GitHub branch protections for your repository.
# Requires GitHub Admin access or GitHub CLI automation via actions

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Run Tests (Windows Only)  # 👈 Make sure this matches the exact name of your CI job
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        required_approving_review_count: 1
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      require_signed_commits: false
