site_name: Ideas Logger
site_description: Documentation for the Ideas Logger project
site_author: Angelos Dimakos

# Repository
repo_name: angelosdimakos/Ideas_Logger
repo_url: https://github.com/angelosdimakos/Ideas_Logger
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - def_list
  - attr_list
  - tables
  - meta
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

# Navigation
nav:
  - Home: index.md
  - API Documentation: api/index.md
  - Test Coverage: coverage/index.md
  - Code Quality: quality/index.md
