[tool.black]
line-length = 100
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.mutmut]
paths_to_mutate = "scripts/ai/"
exclude_paths = "scripts/tests/,*/__init__.py"
use_coverage = true
runner = "pytest"
